config/routes.rb
Rails.application.routes.draw do
  resources :questions

  resources :questions do
  resources :answers

end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, presence: true
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :description, presence: true
  validates :title, length: {maximum: 40, message: "title is too long"}
  has_many :answers
end

app/controllers/answers_controller.rb
require "pry"
class AnswersController < ApplicationController

  def create
    # binding.pry
    @answer = Answer.new(question_id: params["question_id"], description: params["answer"][:description])
    if @answer.save
      flash[:notice] = "Your answer was submitted!"
      redirect_to question_path(@answer.question)
    else
      flash.now[:notice] = "There were problems processing your answer!"
      render :index
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def new
    @question = Question.new
  end

  def show

    @question = Question.find(params[:id])
    @answer = Answer.new

  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Your question was submitted!"
      redirect_to questions_path
    else
      # flash.now[:notice] = "There were problems processing your order!"
      render :new
    end
  end



    def edit
      @question = Question.find(params[:id])

    end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Your question was updated!"
    else
      render "form"
    end
  redirect_to questions_path
  end

    def destroy
      @question = Question.find(params[:id])
      @question.destroy
      redirect_to questions_path, :flash => { :success => "Question deleted!" }
    end



private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Questions/_answer_form.html.erb
<%= form_for @answer,url: question_answers_path(@question) do |f| %>
  <p>
    <%= f.label :Your_answer %><br />
    <%= f.text_area :description, rows:5 %>
  </p>
  <p><%= f.submit "Answer this question" %></p>
<% end %>

app/views/Questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, rows:5 %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/Questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>
<%= link_to "Home", questions_path %>

app/views/Questions/index.html.erb
<h3>Questions </h3>
  <% @questions.each do |question|%>


      <li><%= question.title %></li>
      <p><%= link_to "Show more", question %></p>


        <% end %>

app/views/Questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<div data-alert >
    <% @question.errors.full_messages.each do |error| %>
      <%= error %>
      <a href="#" class="close">&times;</a>
    <% end %>

</div>

app/views/Questions/show.html.erb
<h3>
Question: <%= @question.title %>
</h3>

<div class="errors">
  <ul>
    <% @question.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
</div>

<%= @question.description %>
<p>
<td><%= link_to "Edit", edit_question_path(@question) %><td>
<td><%= link_to "Delete", {:controller => "questions",:action =>
  'destroy', :id => @question.id }, :method => :delete %></td>
</p>

<p>
  <h3>Answers:</h3>
  <% @question.answers.each do |answer|%>
    <li><%= answer.description %></li>
  <% end %>
</p>
<%= render 'answer_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">

       <ul class="button-group">
         <li><a href="/questions" class="button">Home</a></li>
         <li><a href="/questions/new" class="button">New Question</a></li>
        </ul>
      </div>
      <h1>StackOverflow</h1>
      <hr/>
    </div>
  </div>






 <div class="row">
    <div class="large-12 columns">
      <div><h5><%= notice %></h5></div>
      <div class="panel">
        <h5><%= yield %></h5>
      </div>
    </div>
  </div>



  <footer class="row">
    <div class="large-12 columns">
      <hr/>


        <div class="large-6 columns">
          StackOverflow_Demo/Learning Rails
        </div>
      </div>
    </div>
  </footer>

</body>
</html>